In [59]:
import numpy as np
import matplotlib.pyplot as plt

from hmmlearn import hmm
import yfinance as yf
import pandas as pd

In [60]:
df = yf.download('^RUA',start = '2000-01-01')
df.reset_index(inplace = True) #resetting index
df.head() # display

[*********************100%***********************]  1 of 1 completed

,Date,Open,High,Low,Close,Adj Close,Volume
0,2000-01-03,793.309998,798.419983,776.400024,786.200012,786.200012,0
1,2000-01-04,786.270020,786.270020,754.739990,755.799988,755.799988,0
2,2000-01-05,755.799988,762.210022,742.820007,757.090027,757.090027,0
3,2000-01-06,757.090027,761.960022,751.590027,756.729980,756.729980,0
4,2000-01-07,756.729980,777.250000,755.460022,777.250000,777.250000,0

In [61]:
df['pct_ret'] = df['Adj Close'].pct_change()
df['state'] = df['pct_ret'].apply(lambda x: 2 if (x > 0.001)\
else (0 if (x < -0.001)\
else 1))
df.dropna(inplace = True)
df.tail()

,Date,Open,High,Low,Close,Adj Close,Volume,pct_ret,state
5526,2022-01-31,2566.699951,2622.290039,2558.979980,2621.969971,2621.969971,0,0.021498,2
5527,2022-02-01,2622.000000,2644.320068,2602.290039,2642.229980,2642.229980,0,0.007727,2
5528,2022-02-02,2642.379883,2662.360107,2634.629883,2659.229980,2659.229980,0,0.006434,2
5529,2022-02-03,2658.280029,2658.280029,2590.780029,2594.100098,2594.100098,0,-0.024492,0
5530,2022-02-04,2593.709961,2632.350098,2580.100098,2610.659912,2610.659912,0,0.006384,2

In [62]:
X = df[['Adj Close','pct_ret']].to_numpy()
y = data['state']

In [63]:
# Build an HMM instance and set parameters
remodel = hmm.GaussianHMM(n_components=3, covariance_type="full", n_iter=100)
remodel.fit(X)

Z2 = remodel.predict(X)

In [64]:
Z = pd.DataFrame(Z2)
Z.value_counts()

0    3345
2    1104
1    1081
dtype: int64

In [45]:
y.value_counts()

up           2644
down         2215
no_change     671
Name: state, dtype: int64

In [58]:
model1 = hmm.MultinomialHMM(n_components=3)
model1.fit(X,y)

# y_pred = model1.predict(X)

ValueError: Symbols should be integers

In [51]:
import seqlearn
# from seqlearn import hmm
model1 = seqlearn.hmm.MultinomialHMM(n_components=3)
model1.fit(X)

y_pred = model1.predict(X)

AttributeError: module 'seqlearn' has no attribute 'hmm'

In [1]:
from ta import add_all_ta_features
from ta.utils import dropna
from ta.volatility import BollingerBands

In [3]:
import pandas as pd
from ta import add_all_ta_features
from ta.utils import dropna
import yfinance as yf

df = yf.download('^RUA',start = '2000-01-01')
df.reset_index(inplace = True) #resetting index
df.head() # display

# Add ta features filling NaN values
df = add_all_ta_features(
    df, open="Open", high="High", low="Low", close="Close", volume="Volume", fillna=True)

[*********************100%***********************]  1 of 1 completed

C:\Users\lemon\anaconda3\lib\site-packages\ta\trend.py:769: RuntimeWarning: invalid value encountered in double_scalars
  dip[idx] = 100 * (self._dip[idx] / value)
C:\Users\lemon\anaconda3\lib\site-packages\ta\trend.py:774: RuntimeWarning: invalid value encountered in double_scalars
  din[idx] = 100 * (self._din[idx] / value)

In [4]:
df

,Date,Open,High,Low,Close,Adj Close,Volume,volume_adi,volume_obv,volume_cmf,...,momentum_wr,momentum_ao,momentum_roc,momentum_ppo,momentum_ppo_signal,momentum_ppo_hist,momentum_kama,others_dr,others_dlr,others_cr
0,2000-01-03,793.309998,798.419983,776.400024,786.200012,786.200012,0,-0.000000e+00,0,0.000000,...,-55.494976,0.000000,0.000000,0.0,0.0,0.000000e+00,786.200012,-24.549331,0.000000,0.000000
1,2000-01-04,786.270020,786.270020,754.739990,755.799988,755.799988,0,-0.000000e+00,0,0.000000,...,-97.573265,0.000000,0.000000,0.0,0.0,0.000000e+00,771.754293,-3.866704,-3.943445,-3.866704
2,2000-01-05,755.799988,762.210022,742.820007,757.090027,757.090027,0,0.000000e+00,0,0.000000,...,-74.334486,0.000000,0.000000,0.0,0.0,0.000000e+00,764.689514,0.170685,0.170540,-3.702618
3,2000-01-06,757.090027,761.960022,751.590027,756.729980,756.729980,0,0.000000e+00,0,0.000000,...,-74.982052,0.000000,0.000000,0.0,0.0,0.000000e+00,761.089367,-0.047557,-0.047568,-3.748414
4,2000-01-07,756.729980,777.250000,755.460022,777.250000,777.250000,0,0.000000e+00,0,0.000000,...,-38.075526,0.000000,0.000000,0.0,0.0,0.000000e+00,768.224424,2.711670,2.675556,-1.138389
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5531,2022-02-07,2610.709961,2625.189941,2596.939941,2603.570068,2603.570068,0,2.357096e+07,8420800,0.758292,...,-33.763149,-60.267166,0.019593,-100.0,-100.0,-1.494826e-09,2562.723816,-0.271573,-0.271942,231.158742
5532,2022-02-08,2602.929932,2633.120117,2593.729980,2627.810059,2627.810059,0,2.357096e+07,8420800,0.758292,...,-21.898357,-60.419490,2.948828,-100.0,-100.0,-1.366047e-09,2567.231243,0.931029,0.926722,234.241925
5533,2022-02-09,2628.360107,2670.100098,2628.360107,2669.320068,2669.320068,0,2.357096e+07,8420800,0.758292,...,-0.358552,-58.833648,4.028532,-100.0,-100.0,-1.248367e-09,2578.589961,1.579643,1.567296,239.521754
5534,2022-02-10,2668.489990,2674.540039,2610.729980,2622.479980,2622.479980,0,2.357096e+07,8420800,0.758292,...,-23.451534,-52.455004,3.598832,-100.0,-100.0,-1.140805e-09,2581.618865,-1.754757,-1.770336,233.563971
5535,2022-02-11,2622.699951,2635.560059,2563.649902,2573.780029,2573.780029,0,2.357096e+07,8420800,0.758292,...,-53.118267,-48.951818,1.987223,-100.0,-100.0,-1.042523e-09,2581.572623,-1.857019,-1.874478,227.369625

In [ ]:
def train(df, parameter):
    X = ['','']
    y = 

    for parameter
        model.fit
        model.predict
    
    # compare

    return model