In [4]:
pip install ta

Requirement already satisfied: ta in c:\users\lemon\anaconda3\lib\site-packages (0.8.0)
Requirement already satisfied: numpy in c:\users\lemon\anaconda3\lib\site-packages (from ta) (1.20.3)
Requirement already satisfied: pandas in c:\users\lemon\anaconda3\lib\site-packages (from ta) (1.3.4)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\lemon\anaconda3\lib\site-packages (from pandas->ta) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in c:\users\lemon\anaconda3\lib\site-packages (from pandas->ta) (2021.3)
Requirement already satisfied: six>=1.5 in c:\users\lemon\anaconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas->ta) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
from ta import add_all_ta_features
from ta.utils import dropna
from ta.trend import ema_indicator
import yfinance as yf

df = yf.download('^RUA',start = '2000-01-01')
df.reset_index(inplace = True) #resetting index

# Clean NaN values
df = dropna(df)

# Add ta features filling NaN values
df = add_all_ta_features(df, open="Open", high="High", low="Low", close="Close", volume="Volume", fillna=True)

[*********************100%***********************]  1 of 1 completed

C:\Users\lemon\anaconda3\lib\site-packages\ta\trend.py:769: RuntimeWarning: invalid value encountered in double_scalars
  dip[idx] = 100 * (self._dip[idx] / value)
C:\Users\lemon\anaconda3\lib\site-packages\ta\trend.py:774: RuntimeWarning: invalid value encountered in double_scalars
  din[idx] = 100 * (self._din[idx] / value)

In [3]:
df

,Date,Open,High,Low,Close,Adj Close,Volume,volume_adi,volume_obv,volume_cmf,...,momentum_wr,momentum_ao,momentum_roc,momentum_ppo,momentum_ppo_signal,momentum_ppo_hist,momentum_kama,others_dr,others_dlr,others_cr
1274,2005-01-28,670.090027,670.669983,665.429993,668.150024,668.150024,3474600.0,1.326671e+05,3474600.0,0.038182,...,-48.090901,0.000000,0.000000,0.000000,0.000000,0.000000,668.150024,-12.150009,0.000000,0.000000
1275,2005-01-31,668.150024,674.659973,668.150024,674.539978,674.539978,3228800.0,3.242437e+06,6703400.0,0.483700,...,-1.300058,0.000000,0.000000,-0.567296,-0.113459,-0.453837,668.190305,0.956365,0.951821,0.956365
1276,2005-02-01,674.539978,679.869995,674.500000,679.380005,679.380005,3368500.0,5.996213e+06,10071900.0,0.595341,...,-3.393284,0.000000,0.000000,-0.684161,-0.227600,-0.456561,668.255432,0.717530,0.714968,1.680757
1277,2005-02-02,679.380005,682.770020,679.119995,681.780029,681.780029,3272600.0,7.493569e+06,13344500.0,0.561547,...,-5.709277,0.000000,0.000000,-0.992615,-0.380603,-0.612013,671.593009,0.353267,0.352644,2.039962
1278,2005-02-03,681.780029,681.780029,677.330017,679.840027,679.840027,3254600.0,7.910455e+06,10089900.0,0.476559,...,-16.897279,0.000000,0.000000,-1.267679,-0.558018,-0.709661,674.196293,-0.284550,-0.284955,1.749607
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5177,2020-09-09,1943.729980,1993.760010,1943.729980,1980.150024,1980.150024,4975100.0,1.310718e+07,21140700.0,0.046287,...,-3.688585,635.981685,179.828443,78.082840,37.545869,40.536971,1716.161714,-0.887440,-0.891401,196.363085
5232,2020-11-25,2161.169922,2161.659912,2149.570068,2158.969971,2158.969971,4921900.0,1.583888e+07,26062600.0,0.161149,...,-0.184576,881.643479,205.085783,73.798523,44.796400,29.002124,1898.948159,9.030626,8.645863,223.126527
5243,2020-12-11,2192.949951,2192.949951,2171.189941,2189.510010,2189.510010,4890200.0,1.918294e+07,30952800.0,0.251702,...,-0.231291,1131.519971,209.034581,69.030611,49.643242,19.387369,2020.169834,1.414565,1.404654,227.697363
5252,2020-12-24,2226.149902,2229.050049,2220.989990,2228.629883,2228.629883,1923800.0,2.090617e+07,32876600.0,0.289605,...,-0.027581,1164.518941,214.112739,58.805715,51.475736,7.329978,2107.259079,1.786695,1.770922,233.552316
5256,2020-12-31,2237.699951,2250.550049,2233.090088,2248.439941,2248.439941,3514200.0,2.357096e+07,36390800.0,0.345893,...,-0.136587,1169.322387,218.624852,53.790549,51.938699,1.851850,2166.277946,0.888890,0.884962,236.517228

In [3]:
ema = ema_indicator(df['Close'], window = 14)

In [4]:
ema

1274            NaN
1275            NaN
1276            NaN
1277            NaN
1278            NaN
           ...
5177    1137.841171
5232    1273.991678
5243    1396.060789
5252    1507.070001
5256    1605.919327
Name: ema_14, Length: 127, dtype: float64